language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script:
- ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
    secure: ptaqt1kvdAEJP+N3jiqLGzsTNE9fxn08o5678z6Zksqr+LIvKcJNl0M+0owLDziobvFnXjQZYjGSHVqVRDqmly9Wdalgs0KES6o1I1eTEZ/JJh95UV3z9WJn7A/Fq2RAaVsyXL8MgiRiwh+XLsmEXtFzi9y/Fk3wrZayUjWNiMUSCrivir35qW0kllgQy45xUx/ZnIqa5PQgjuTJ8y3eRa1gwKZj2aybGLOky/cMtWPXaWfFkgM8zJ62R8tVUBDHbr1hqK6BEHo1eZPv2nYVZHOYpdDVxH3swZqUdq4MrWnVCfUCcA7GNzAILvHcqvTfpYknX4Mqxq8f83vVq2xUsu6Ee3bQ3qH8vMkwRcaA+zGdKMf/em7msrz3R2oNQ62H2wM6s7xnZ4INp7lVPkrStPWnth1T6frkea+93fj96aBzxR+vaHWdNpadArUalu8V6bsm2cUAlNboSVAVe+XABhLBHO/fQs3hqj6WJt0wfqpr9+W0akII0bvv4qgBKSKOIIibfpcNDa1iF0b7RNQpBqmBlHRoPzyBp5u7kGqas34U7EOl4T3aq6iePHS4XCJehSiVLTl6KOTd5x6pzTk3hY3g6+yJBzekDiuzbqtJhbIIqx+BI+Luei/trvdiQvwKgR09fyfCiXChDoMM7Y/oou4CDvs0FOh59nRnQ+FbyEQ=
